# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Dec 02 22:14:08 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainUi(object):
    def setupUi(self, MainUi):
        MainUi.setObjectName(_fromUtf8("MainUi"))
        MainUi.setWindowModality(QtCore.Qt.NonModal)
        MainUi.resize(821, 770)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        MainUi.setFont(font)
        MainUi.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainUi.setAnimated(True)
        MainUi.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainUi)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.centralwidget_functions = QtGui.QWidget(self.centralwidget)
        self.centralwidget_functions.setObjectName(_fromUtf8("centralwidget_functions"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget_functions)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.functions_search_input = QtGui.QLineEdit(self.centralwidget_functions)
        self.functions_search_input.setEnabled(False)
        self.functions_search_input.setObjectName(_fromUtf8("functions_search_input"))
        self.horizontalLayout.addWidget(self.functions_search_input)
        self.functions_addfeed_easy_button = QtGui.QPushButton(self.centralwidget_functions)
        self.functions_addfeed_easy_button.setEnabled(False)
        self.functions_addfeed_easy_button.setObjectName(_fromUtf8("functions_addfeed_easy_button"))
        self.horizontalLayout.addWidget(self.functions_addfeed_easy_button)
        self.functions_addfeed_manual_button = QtGui.QPushButton(self.centralwidget_functions)
        self.functions_addfeed_manual_button.setObjectName(_fromUtf8("functions_addfeed_manual_button"))
        self.horizontalLayout.addWidget(self.functions_addfeed_manual_button)
        self.functions_updatefeeds = QtGui.QPushButton(self.centralwidget_functions)
        self.functions_updatefeeds.setObjectName(_fromUtf8("functions_updatefeeds"))
        self.horizontalLayout.addWidget(self.functions_updatefeeds)
        self.verticalLayout.addWidget(self.centralwidget_functions)
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.tab_feed = QtGui.QWidget()
        self.tab_feed.setAcceptDrops(True)
        self.tab_feed.setObjectName(_fromUtf8("tab_feed"))
        self.gridLayout = QtGui.QGridLayout(self.tab_feed)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rssitemlist = QtGui.QListWidget(self.tab_feed)
        self.rssitemlist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.rssitemlist.setAlternatingRowColors(True)
        self.rssitemlist.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.rssitemlist.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.rssitemlist.setProperty("isWrapping", False)
        self.rssitemlist.setResizeMode(QtGui.QListView.Adjust)
        self.rssitemlist.setWordWrap(False)
        self.rssitemlist.setObjectName(_fromUtf8("rssitemlist"))
        self.gridLayout.addWidget(self.rssitemlist, 0, 1, 1, 1)
        self.feedlist = QtGui.QTreeWidget(self.tab_feed)
        self.feedlist.setMaximumSize(QtCore.QSize(215, 16777215))
        self.feedlist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.feedlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.feedlist.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.EditKeyPressed)
        self.feedlist.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.feedlist.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.feedlist.setAlternatingRowColors(False)
        self.feedlist.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.feedlist.setIndentation(15)
        self.feedlist.setAnimated(True)
        self.feedlist.setWordWrap(True)
        self.feedlist.setObjectName(_fromUtf8("feedlist"))
        self.feedlist.header().setVisible(False)
        self.gridLayout.addWidget(self.feedlist, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_feed, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_settings)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.settings_basic_group = QtGui.QGroupBox(self.tab_settings)
        self.settings_basic_group.setObjectName(_fromUtf8("settings_basic_group"))
        self.gridLayout_2 = QtGui.QGridLayout(self.settings_basic_group)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.basic_dlfolder_label = QtGui.QLabel(self.settings_basic_group)
        self.basic_dlfolder_label.setObjectName(_fromUtf8("basic_dlfolder_label"))
        self.gridLayout_2.addWidget(self.basic_dlfolder_label, 0, 0, 1, 1)
        self.basic_dlfolder_input = QtGui.QLineEdit(self.settings_basic_group)
        self.basic_dlfolder_input.setObjectName(_fromUtf8("basic_dlfolder_input"))
        self.gridLayout_2.addWidget(self.basic_dlfolder_input, 1, 0, 1, 1)
        self.basic_db_reload_button = QtGui.QPushButton(self.settings_basic_group)
        self.basic_db_reload_button.setObjectName(_fromUtf8("basic_db_reload_button"))
        self.gridLayout_2.addWidget(self.basic_db_reload_button, 4, 0, 1, 1)
        self.basic_autotrack_input = QtGui.QCheckBox(self.settings_basic_group)
        self.basic_autotrack_input.setEnabled(False)
        self.basic_autotrack_input.setObjectName(_fromUtf8("basic_autotrack_input"))
        self.gridLayout_2.addWidget(self.basic_autotrack_input, 2, 0, 1, 1)
        self.basic_debuglog_input = QtGui.QCheckBox(self.settings_basic_group)
        self.basic_debuglog_input.setEnabled(False)
        self.basic_debuglog_input.setObjectName(_fromUtf8("basic_debuglog_input"))
        self.gridLayout_2.addWidget(self.basic_debuglog_input, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.settings_basic_group, 0, 0, 1, 1)
        self.settings_sqlite_group = QtGui.QGroupBox(self.tab_settings)
        self.settings_sqlite_group.setObjectName(_fromUtf8("settings_sqlite_group"))
        self.gridLayout_5 = QtGui.QGridLayout(self.settings_sqlite_group)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sqlite_dbpath_input = QtGui.QLineEdit(self.settings_sqlite_group)
        self.sqlite_dbpath_input.setObjectName(_fromUtf8("sqlite_dbpath_input"))
        self.gridLayout_5.addWidget(self.sqlite_dbpath_input, 1, 0, 1, 1)
        self.sqlite_dbpath_label = QtGui.QLabel(self.settings_sqlite_group)
        self.sqlite_dbpath_label.setObjectName(_fromUtf8("sqlite_dbpath_label"))
        self.gridLayout_5.addWidget(self.sqlite_dbpath_label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.settings_sqlite_group, 1, 0, 1, 1)
        self.settings_mysql_group = QtGui.QGroupBox(self.tab_settings)
        self.settings_mysql_group.setEnabled(False)
        self.settings_mysql_group.setObjectName(_fromUtf8("settings_mysql_group"))
        self.gridLayout_3 = QtGui.QGridLayout(self.settings_mysql_group)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mysql_dbname_label = QtGui.QLabel(self.settings_mysql_group)
        self.mysql_dbname_label.setObjectName(_fromUtf8("mysql_dbname_label"))
        self.gridLayout_3.addWidget(self.mysql_dbname_label, 9, 0, 1, 1)
        self.mysql_dbname_input = QtGui.QLineEdit(self.settings_mysql_group)
        self.mysql_dbname_input.setObjectName(_fromUtf8("mysql_dbname_input"))
        self.gridLayout_3.addWidget(self.mysql_dbname_input, 10, 0, 1, 1)
        self.mysql_username_input = QtGui.QLineEdit(self.settings_mysql_group)
        self.mysql_username_input.setObjectName(_fromUtf8("mysql_username_input"))
        self.gridLayout_3.addWidget(self.mysql_username_input, 12, 0, 1, 1)
        self.mysql_password_input = QtGui.QLineEdit(self.settings_mysql_group)
        self.mysql_password_input.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.mysql_password_input.setEchoMode(QtGui.QLineEdit.Password)
        self.mysql_password_input.setObjectName(_fromUtf8("mysql_password_input"))
        self.gridLayout_3.addWidget(self.mysql_password_input, 14, 0, 1, 1)
        self.mysql_port_input = QtGui.QLineEdit(self.settings_mysql_group)
        self.mysql_port_input.setObjectName(_fromUtf8("mysql_port_input"))
        self.gridLayout_3.addWidget(self.mysql_port_input, 8, 0, 1, 1)
        self.mysql_port_label = QtGui.QLabel(self.settings_mysql_group)
        self.mysql_port_label.setObjectName(_fromUtf8("mysql_port_label"))
        self.gridLayout_3.addWidget(self.mysql_port_label, 6, 0, 1, 1)
        self.mysql_address_input = QtGui.QLineEdit(self.settings_mysql_group)
        self.mysql_address_input.setObjectName(_fromUtf8("mysql_address_input"))
        self.gridLayout_3.addWidget(self.mysql_address_input, 4, 0, 1, 1)
        self.mysql_address_label = QtGui.QLabel(self.settings_mysql_group)
        self.mysql_address_label.setObjectName(_fromUtf8("mysql_address_label"))
        self.gridLayout_3.addWidget(self.mysql_address_label, 3, 0, 1, 1)
        self.mysql_username_label = QtGui.QLabel(self.settings_mysql_group)
        self.mysql_username_label.setObjectName(_fromUtf8("mysql_username_label"))
        self.gridLayout_3.addWidget(self.mysql_username_label, 11, 0, 1, 1)
        self.mysql_password_label = QtGui.QLabel(self.settings_mysql_group)
        self.mysql_password_label.setObjectName(_fromUtf8("mysql_password_label"))
        self.gridLayout_3.addWidget(self.mysql_password_label, 13, 0, 1, 1)
        self.mysql_usemysql_input = QtGui.QCheckBox(self.settings_mysql_group)
        self.mysql_usemysql_input.setObjectName(_fromUtf8("mysql_usemysql_input"))
        self.gridLayout_3.addWidget(self.mysql_usemysql_input, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.settings_mysql_group, 2, 0, 1, 1)
        self.tabs.addTab(self.tab_settings, _fromUtf8(""))
        self.tab_debug = QtGui.QWidget()
        self.tab_debug.setObjectName(_fromUtf8("tab_debug"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_debug)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.debug_buttons = QtGui.QGroupBox(self.tab_debug)
        self.debug_buttons.setObjectName(_fromUtf8("debug_buttons"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.debug_buttons)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.debug_print_iros = QtGui.QPushButton(self.debug_buttons)
        self.debug_print_iros.setObjectName(_fromUtf8("debug_print_iros"))
        self.horizontalLayout_2.addWidget(self.debug_print_iros)
        self.debug_print_threads = QtGui.QPushButton(self.debug_buttons)
        self.debug_print_threads.setObjectName(_fromUtf8("debug_print_threads"))
        self.horizontalLayout_2.addWidget(self.debug_print_threads)
        self.verticalLayout_2.addWidget(self.debug_buttons)
        self.debug_textedit = QtGui.QPlainTextEdit(self.tab_debug)
        self.debug_textedit.setObjectName(_fromUtf8("debug_textedit"))
        self.verticalLayout_2.addWidget(self.debug_textedit)
        self.tabs.addTab(self.tab_debug, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabs)
        MainUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainUi)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainUi.setStatusBar(self.statusbar)
        self.actionRSSAddFeed = QtGui.QAction(MainUi)
        self.actionRSSAddFeed.setObjectName(_fromUtf8("actionRSSAddFeed"))
        self.actionRSSRemoveFeed = QtGui.QAction(MainUi)
        self.actionRSSRemoveFeed.setObjectName(_fromUtf8("actionRSSRemoveFeed"))
        self.actionRSSUpdateFeed = QtGui.QAction(MainUi)
        self.actionRSSUpdateFeed.setObjectName(_fromUtf8("actionRSSUpdateFeed"))
        self.actionRSSUpdateAllFeeds = QtGui.QAction(MainUi)
        self.actionRSSUpdateAllFeeds.setObjectName(_fromUtf8("actionRSSUpdateAllFeeds"))
        self.actionDLItem = QtGui.QAction(MainUi)
        self.actionDLItem.setObjectName(_fromUtf8("actionDLItem"))
        self.actionListDLItems = QtGui.QAction(MainUi)
        self.actionListDLItems.setObjectName(_fromUtf8("actionListDLItems"))

        self.retranslateUi(MainUi)
        self.tabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.basic_db_reload_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainUi.SettingsDBReload)
        QtCore.QObject.connect(self.basic_autotrack_input, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainUi.SettingsBasicChanged)
        QtCore.QObject.connect(self.basic_dlfolder_input, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), MainUi.SettingsBasicChanged)
        QtCore.QObject.connect(self.actionRSSAddFeed, QtCore.SIGNAL(_fromUtf8("triggered()")), MainUi.RSSAddFeedE)
        QtCore.QObject.connect(self.actionRSSRemoveFeed, QtCore.SIGNAL(_fromUtf8("triggered()")), MainUi.RSSRemoveFeed)
        QtCore.QObject.connect(self.feedlist, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainUi.RSSContextMenu)
        QtCore.QObject.connect(self.rssitemlist, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MainUi.RSSFeedItemContextMenu)
        QtCore.QObject.connect(self.actionDLItem, QtCore.SIGNAL(_fromUtf8("triggered()")), MainUi.SettingsBasicChanged)
        QtCore.QObject.connect(self.functions_addfeed_easy_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainUi.RSSAddFeedE)
        QtCore.QObject.connect(self.functions_addfeed_manual_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainUi.RSSAddFeedM)
        QtCore.QObject.connect(self.functions_updatefeeds, QtCore.SIGNAL(_fromUtf8("clicked()")), MainUi.RSSUpdateAllFeeds)
        QtCore.QObject.connect(self.debug_print_iros, QtCore.SIGNAL(_fromUtf8("clicked()")), MainUi.DebugPrintIROs)
        QtCore.QObject.connect(self.debug_print_threads, QtCore.SIGNAL(_fromUtf8("clicked()")), MainUi.DebugPrintThreads)
        QtCore.QObject.connect(self.feedlist, QtCore.SIGNAL(_fromUtf8("itemClicked(QTreeWidgetItem*,int)")), MainUi.RSSActivateDetails)
        QtCore.QObject.connect(self.actionDLItem, QtCore.SIGNAL(_fromUtf8("triggered()")), MainUi.DLDLItems)
        QtCore.QMetaObject.connectSlotsByName(MainUi)

    def retranslateUi(self, MainUi):
        MainUi.setWindowTitle(QtGui.QApplication.translate("MainUi", "pyRSSDownloader", None, QtGui.QApplication.UnicodeUTF8))
        self.functions_search_input.setText(QtGui.QApplication.translate("MainUi", "Search feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.functions_addfeed_easy_button.setText(QtGui.QApplication.translate("MainUi", "Add Feed (Easy)", None, QtGui.QApplication.UnicodeUTF8))
        self.functions_addfeed_manual_button.setText(QtGui.QApplication.translate("MainUi", "Add Feed (Manual)", None, QtGui.QApplication.UnicodeUTF8))
        self.functions_updatefeeds.setText(QtGui.QApplication.translate("MainUi", "Update All Feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.feedlist.setSortingEnabled(True)
        self.tabs.setTabText(self.tabs.indexOf(self.tab_feed), QtGui.QApplication.translate("MainUi", "Feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_basic_group.setTitle(QtGui.QApplication.translate("MainUi", "Basic Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.basic_dlfolder_label.setText(QtGui.QApplication.translate("MainUi", "RSS Download Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.basic_dlfolder_input.setText(QtGui.QApplication.translate("MainUi", "C:\\RSSFeedDownloads", None, QtGui.QApplication.UnicodeUTF8))
        self.basic_db_reload_button.setText(QtGui.QApplication.translate("MainUi", "Force Database Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.basic_autotrack_input.setText(QtGui.QApplication.translate("MainUi", "Automatically track when feeds are on hold", None, QtGui.QApplication.UnicodeUTF8))
        self.basic_debuglog_input.setText(QtGui.QApplication.translate("MainUi", "Enable debug logging", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_sqlite_group.setTitle(QtGui.QApplication.translate("MainUi", "SQLite Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.sqlite_dbpath_input.setText(QtGui.QApplication.translate("MainUi", "pyrssdb", None, QtGui.QApplication.UnicodeUTF8))
        self.sqlite_dbpath_label.setText(QtGui.QApplication.translate("MainUi", "Database Path", None, QtGui.QApplication.UnicodeUTF8))
        self.settings_mysql_group.setTitle(QtGui.QApplication.translate("MainUi", "MySQL Settings (Shared Database)", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_dbname_label.setText(QtGui.QApplication.translate("MainUi", "Database Name", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_dbname_input.setText(QtGui.QApplication.translate("MainUi", "pyrssdl", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_username_input.setText(QtGui.QApplication.translate("MainUi", "pyrss", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_password_input.setText(QtGui.QApplication.translate("MainUi", "pyrss123", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_port_input.setText(QtGui.QApplication.translate("MainUi", "3306", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_port_label.setText(QtGui.QApplication.translate("MainUi", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_address_input.setText(QtGui.QApplication.translate("MainUi", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_address_label.setText(QtGui.QApplication.translate("MainUi", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_username_label.setText(QtGui.QApplication.translate("MainUi", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_password_label.setText(QtGui.QApplication.translate("MainUi", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.mysql_usemysql_input.setText(QtGui.QApplication.translate("MainUi", "Use MySQL instead of SQLite (will attempt to transfer database on first connection)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_settings), QtGui.QApplication.translate("MainUi", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.debug_buttons.setTitle(QtGui.QApplication.translate("MainUi", "Debug Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.debug_print_iros.setText(QtGui.QApplication.translate("MainUi", "Print IROs", None, QtGui.QApplication.UnicodeUTF8))
        self.debug_print_threads.setText(QtGui.QApplication.translate("MainUi", "Print Threads", None, QtGui.QApplication.UnicodeUTF8))
        self.debug_textedit.setPlainText(QtGui.QApplication.translate("MainUi", "Waiting for action...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_debug), QtGui.QApplication.translate("MainUi", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSAddFeed.setText(QtGui.QApplication.translate("MainUi", "Add RSS Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSAddFeed.setToolTip(QtGui.QApplication.translate("MainUi", "Add a new RSS feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSRemoveFeed.setText(QtGui.QApplication.translate("MainUi", "Remove RSS Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSRemoveFeed.setToolTip(QtGui.QApplication.translate("MainUi", "Remove this RSS feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSUpdateFeed.setText(QtGui.QApplication.translate("MainUi", "Update RSS Feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSUpdateFeed.setToolTip(QtGui.QApplication.translate("MainUi", "Update selected RSS feed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSUpdateAllFeeds.setText(QtGui.QApplication.translate("MainUi", "Update All RSS Feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRSSUpdateAllFeeds.setToolTip(QtGui.QApplication.translate("MainUi", "Update all RSS feeds", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDLItem.setText(QtGui.QApplication.translate("MainUi", "Download Item(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDLItem.setToolTip(QtGui.QApplication.translate("MainUi", "Download Item(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListDLItems.setText(QtGui.QApplication.translate("MainUi", "Download Item(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListDLItems.setToolTip(QtGui.QApplication.translate("MainUi", "Download Item(s)", None, QtGui.QApplication.UnicodeUTF8))

